version: '2.1'

services:
  pv_limiter:
    image: pv_plant_limiter:latest
    container_name: PvLimiter
    restart: always
    build: .
    environment:
      - TZ=Europe/Zurich
      - LIMITER_INTERVAL=20.0             # cyclic interval of limiter algo
      - MAX_AC_PWR=600                    # max allowed AC Power of all inerverts
      - INCREMENT=20                      # increment used for shadow function
      - BROKER_IP=192.168.0.2             # mqtt broker ip
      - BROKER_PORT=1886                  # mqtt broker port
      - DTU_TOPIC=solar/                  # openDTU base topic
      - LIMITER_TOPIC=limiter/            # limiter base topic
      - SN_INV=1,2                        # Inverter 1 = south, Inverter 2 = north

